language: python
sudo: true

python:
  - 2.7
  # - 3.5

notifications:
  email: false

services:
  - docker

addons:
  hosts:
    - ci_head_1
    - ci_compute_1

before_install:
  # Download vagrant insecurekey
  - mkdir -p ~/.vagrant.d/
  - wget https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant -O ~/.vagrant.d/insecure_private_key
  - chmod 600 ~/.vagrant.d/insecure_private_key

  # Start docker containers
  - docker version
  - docker-compose version
  - pushd ci
  - docker build -t "dask-ec2-test" .
  - docker-compose up -d
  - docker ps
  - docker images
  - popd
  - export TEST_CLUSTERFILE=$(pwd)/ci/cluster_docker.yaml

  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install -r requirements.txt

  # Mock credentials
  - export AWS_ACCESS_KEY_ID=1
  - export AWS_SECRET_ACCESS_KEY=1

install:
  - which python
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - travis_wait 50 py.test --pyargs dask_ec2 --cov=dask_ec2 --cov-report term-missing --cov-report html -s -vv
